export const USERS_HAS_ERROR = 'USERS_HAS_ERROR';
export const USERS_IS_LOADING = 'USERS_IS_LOADING';
export const USERS_FETCH_DATA_SUCCESS = 'USERS_FETCH_DATA_SUCCESS';

export const USER_HAS_BEEN_DELETED = 'USER_HAS_BEEN_DELETED';
export const USER_HAS_BEEN_UPDATED = 'USER_HAS_BEEN_UPDATED';

export const MODAL_OPEN = 'MODAL_OPEN';
export const MODAL_CLOSE = 'MODAL_CLOSE';